### ISSUE TITLE
add s3 performance enhancement defaults to awscreds

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-switch-account#22]

**Comment by dtenenba** [comment]
example of a profile containing creds and config: 

```
cat ~/.aws/credentials 
[rmcdermo-hse]
aws_access_key_id = ***************
aws_secret_access_key = ****************************
s3 =
  max_concurrent_requests = 100 
  max_queue_size = 10000
  multipart_threshold = 64MB
  multipart_chunksize = 16MB


```

**Comment by dtenenba** [comment]
@dirkpetersen  Talking to @robert-mcdermott I'm not sure we want to change these defaults, or at least not set them so high. See https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#max-concurrent-requests where it says if the number is too high, it could overwhelm a system. Since we have shared home directories, there's no telling whether the user is on a laptop with 2 cores or on a rhino or gizmo node with tons of cores. 

And for `max_queue_size` it says you don't generally need to change the value. The other parameters (`multipart_*`) seem like you should only change them if you know what you are doing.

I'm inclined to maybe leave this out by default and perhaps the program can link to documentation   saying that you can tune performance by tweaking these. What do you all think? I'm open to other suggestions....

**Comment by dirkpetersen** [comment]
We are optimizing our settings for servers and the awscreds util won't be available on laptops. The problem is that if we do not add a high performance chunk size at upload time there is no way to make things ready fast later, but I am OK if we set the max_concurrent_requests to 30 and max_queue_size to 3000 for now.

Robert, can you confirm that multipart_chunksize and  multipart_threshold are optimized  for bam files > 30G

**Comment by dtenenba** [comment]
@robert-mcdermott see @dirkpetersen 's question in the previous comment. Once I have an answer I will make the change.

**Comment by robert-mcdermott** [comment]
@dirkpetersen @dtenenba  The upload chunk size won't have an impact on future download performance of the objects. Once all the chunks of an object are uploaded and the checksums are good, S3 will concatenate all the intermediate chunks in to a single large object (it works differently than swift, which leaves the data in multipart chunks with a manifest).

I don't know what the optimal size of the multipart_threshold/chunks size is for large BAM files, but after some searching on the net (can't find the original source for this info) I settled on the the following settings: 

```
max_concurrent_requests = 100
max_queue_size = 10000
multipart_threshold = 64MB
multipart_chunksize = 16MB
```

I figure that you don't want to bother chunking up small files (<64MB) as it's too much overhead and larger chunks should get better performance with a 10Gb network.  These are the settings I've been using for the large nyc genome stuff and it's worked pretty good.  The only non-default setting our friend Mark uses is setting the concurrency to 100: (http://tech.marksblogg.com/billion-nyc-taxi-rides-aws-ec2-p2-8xlarge-mapd.html) 

The defaults for s3 are the following:

```
max_concurrent_requests = 10
max_queue_size = 1000
multipart_threshold = 8MB
multipart_chunksize = 8MB
```
